#!/usr/bin/zsh

clean()
{
  	for i in pyc o Makefile Makefile.Debug Makefile.Release
	do
		find . -name "*.${i}" -exec rm {} \;
	done
}

new_sandbox_project()
{
    if [[ $# > 1 ]]
    then
        echo 'Only one arguments can be used.'
    fi
    pushd ~/projects/dev/sandbox
    mkdir $1
    # if [[ $]]
    # then
    #     echo "$1 already exists."
    # fi
    pushd $1
    git init
    emacs .
}

retry() {
    if [[ $# -lt 3 ]]; then
        echo "usage: retry rep t2sleep command (rep.<=0 means inf.)"
        return
    fi
    ret=0
    rep=$1
    st=$2
    shift 2
    cmd=$*
    echo "Will try $rep times, sleeping $st, the command << $cmd >>"
    res=1
    while [[ $res != 0 ]]
    do
        zsh -c "${cmd}"
        res=$?
        if [[ $res -eq 0 ]]; then
            break
        else
            echo "Fail!"
        fi
        let rep=${rep}-1
        if [[ $rep -eq 0 ]]; then
            break
        elif [[ $st -gt 0 && $rep -gt 0 || $rep -lt 0 ]]; then
            sleep $st
        fi
    done
}

triage_seq() {
    for f in $(find . -type f -name 'S*.JPG' -maxdepth 1); do
        mkdir -p sequences/${f:2:4}
        mv -v $f sequences/${f:2:4}
    done
}

emx() {
    emacsclient -c -e '(load-file "~/.emacs")' -- $@
}


emt() {
    emacsclient -t -e '(load-file "~/.emacs")' -- $@
}

run_chromium() {
    $(which chromium) -proxy-server="socks5://127.0.0.1:9050" --host-resolver-rules="MAP * 0.0.0.0 , EXCLUDE myproxy" --disk-cache-dir=$HOME/.cache.chromium $@ &
}

vpn ()
{
    if [[ $1 == "list" ]]; then
	sudo find /etc/openvpn/client/nordvpn -type f -name "${2}*.nordvpn.com.udp1194.ovpn" | parallel -j8 basename {} | cut -d . -f 1 | sort | column
    else
	sudo ufw disable || return 1
	sudo systemctl $1 openvpn-client@nordvpn_${2} || return 2
	ifconfig | grep -q tun || return 3
	sudo ufw enable || return 4
    fi
}
